[workspace]
resolver = "3"

members = ["foundation-track"]

[workspace.package]
name = "meridian-space"
description = "The Meridian Space Academy course."
version = "0.1.0"
edition = "2024"
homepage = "https://rustycloud.org/index.html"

[workspace.dependencies]
anyhow = "1"
bytes = "1"
num_cpus = "1"
tokio = "1"
tokio-util = "0.7"
tracing = "0.1"
tracing-subscriber = "0.3"
